### ISSUE TITLE
funkcionális követelmények

### ISSUE THREAD

**Issue by lakatosdaniel** [gurubib/pangolin-webshop#1]

**Comment by egytom** [comment]
A use-case diagramon szerepel egy értelmetlen él: **bejelentkezés**---_include_--->**regisztráció**.
Ezt kérlek távoltítsuk el, mert ennek jelentése, hogy minden bejelentkezés magába foglal egy regisztrációt is, ami természetesen felesleges és nem a valós funkcionalitást tükrözi.

**Comment by egytom** [comment]
@lakatosdaniel

**Comment by lakatosdaniel** [comment]
Bocsánat, azt hittem, hogy frissítettem már korábban, de ezek szerint kiment a fejemből. Most megcsináltam!

**Comment by egytom** [comment]
Nem gond, csak azért jeleztem, mert láttam, hogy még nincs kész ez a módosítás. :)
